### ISSUE TITLE
Latest no longer builds

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/ash-molten#4]
This repo no longer builds, does it try to always just get latest MoltenVK? We don't pin it to a specific version?

```sh

========== Building dependency libraries quietly. Please be patient on first build. ==========

still building MoltenVK
still building MoltenVK
still building MoltenVK
still building MoltenVK
still building MoltenVK
still building MoltenVK
still building MoltenVK
still building MoltenVK
still building MoltenVK
still building MoltenVK
========== Done! ==========
xcodebuild -quiet -project "MoltenVKPackaging.xcodeproj" -scheme "MoltenVK Package (macOS only)" build
In file included from /Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm:19:
In file included from /Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.h:24:
In file included from /Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKDevice.h:26:
In file included from /Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/Vulkan/mvk_datatypes.hpp:23:
/Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/API/mvk_datatypes.h:238:1: error: unknown type name 'MTLTextureSwizzle'
MTLTextureSwizzle mvkMTLTextureSwizzleFromVkComponentSwizzle(VkComponentSwizzle vkSwizzle);
^
/Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/API/mvk_datatypes.h:241:1: error: unknown type name 'MTLTextureSwizzleChannels'
MTLTextureSwizzleChannels mvkMTLTextureSwizzleChannelsFromVkComponentMapping(VkComponentMapping vkMapping);
^
In file included from /Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm:19:
In file included from /Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.h:24:
/Users/johan/git/embark/ash-molten/target/debug/build/ash-molten-261694c0a8c71a6c/out/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKDevice.h:293:28: error: unknown type name 'MTLGPUFamily'
        bool getSupportsGPUFamily(MTLGPUFamily gpuFamily);
                                  ^
3 errors generated.
note: Using new build systemnote: Planning buildnote: Constructing build description

--- stderr
```

**Comment by MaikKlein** [comment]
It uses the newest master by default because otherwise we would have to constantly maintain this library.

The intended use case was that the user would compile molten themselves and link it in. Then they have full control over the version.

I don't have a mac at home :(. Looking at the build error, could it be that the newest master of moltenvk is just broken?

**Comment by MaikKlein** [comment]
What version of xcode do you have? The CI should also be broken because it uses `Xcode 10.2` which is `macOS 10.14.4`, and those types require `macOS 10.15+`

**Comment by repi** [comment]
I have `Xcode 10.3` locally. 

Latest [MoltenVK master](https://github.com/KhronosGroup/MoltenVK/commits/master) does build on their CI but they use `Xcode 11.1` on Travis (which was recently added in https://github.com/KhronosGroup/MoltenVK/pull/749) so could be that MoltenVK now requires 11.1 and doesn't build on 10.x anymore.

I'll test and build MoltenVK master on Xcode 10 and see if it works, can file an issue on the repo and see if is supposed to be still be supported.

Unfortunately we can't use or require Xcode 11 ourselves because `physx` doesn't compile on it yet (https://github.com/EmbarkStudios/physx-rs/issues/23)

**Comment by repi** [comment]
https://github.com/KhronosGroup/MoltenVK/issues/770
